/**
 * 정적 아파트 데이터 — 빌드 타임에 포함되어 API 호출 없이 즉시 사용 가능
 * 
 * ⚠️ 이 파일은 자동 생성됩니다. 직접 수정하지 마세요!
 * 동기화: npm run sync-apartments
 * 마지막 동기화: 2026-06-21
 */

export interface StaticApartment {
  name: string;
  dong: string;
  householdCount?: number;
  yearBuilt?: string;
  brand?: string;
}

/** 동별 아파트 데이터 (정렬됨) */
export const APARTMENTS_BY_DONG: Record<string, StaticApartment[]> = {
  '능동': [
    { name: '능동 숲속마을 광명메이루즈', dong: '능동', householdCount: 326, yearBuilt: '2008', brand: '광명주택' },
    { name: '능동 숲속마을 모아미래도 1단지', dong: '능동', householdCount: 870, yearBuilt: '2008', brand: '모아종합건설' },
    { name: '능동 숲속마을 모아미래도 2단지', dong: '능동', householdCount: 361, yearBuilt: '2008', brand: '미래도건설' },
    { name: '능동 숲속마을 자연앤데시앙', dong: '능동', householdCount: 1289, yearBuilt: '2008', brand: '태영건설' },
    { name: '능동 푸른마을 두산위브', dong: '능동', householdCount: 915, yearBuilt: '2007', brand: '두산건설' },
    { name: '능동 푸른마을 모아미래도', dong: '능동', householdCount: 926, yearBuilt: '2008', brand: '모아건설산업' },
    { name: '능동 푸른마을 신일해피트리', dong: '능동', householdCount: 794, yearBuilt: '2008', brand: '신일' },
    { name: '능동 푸른마을 포스코더샵 2차', dong: '능동', householdCount: 1226, yearBuilt: '2008', brand: '포스코건설' },
    { name: '능동역 경남아너스빌', dong: '능동', householdCount: 455, yearBuilt: '2008', brand: '경남기업' },
    { name: '능동역 센트럴 경남아너스빌', dong: '능동', householdCount: 641, yearBuilt: '2008', brand: '경남건설' },
    { name: '능동역 숲속마을 리체더포레스트', dong: '능동', householdCount: 562, yearBuilt: '2008', brand: '풍성주택' },
    { name: '능동역 이지더원', dong: '능동', householdCount: 542, yearBuilt: '2008', brand: '남흥건설' },
  ],
  '목동': [
    { name: '목동 금강펜테리움 센트럴파크 4차', dong: '목동', householdCount: 1195, yearBuilt: '2018', brand: '금강주택' },
    { name: '목동 동원로얄듀크 2차', dong: '목동', householdCount: 761, yearBuilt: '2019', brand: '동원개발' },
    { name: '목동 르파비스', dong: '목동', householdCount: 876, yearBuilt: '2017', brand: '이수건설' },
    { name: '목동 베라체', dong: '목동', householdCount: 859, yearBuilt: '2018', brand: '한일건설' },
    { name: '목동 한신더휴', dong: '목동', householdCount: 930, yearBuilt: '2018', brand: '한신공영' },
    { name: '목동 호반베르디움 2차', dong: '목동', householdCount: 746, yearBuilt: '2017', brand: '호반건설주택' },
    { name: '목동 호반베르디움 센트럴포레', dong: '목동', householdCount: 1695, yearBuilt: '2017', brand: '호반건설' },
    { name: '목동 힐스테이트', dong: '목동', householdCount: 1479, yearBuilt: '2019', brand: '현대건설' },
    { name: '목동 e편한세상', dong: '목동', householdCount: 1526, yearBuilt: '2018', brand: '대림산업' },
  ],
  '반송동': [
    { name: '나루마을 동탄역 유보라 여울숲 1.0', dong: '반송동', householdCount: 568, yearBuilt: '2007', brand: '월드건설' },
    { name: '나루마을 동탄역 유보라 여울숲 2.0', dong: '반송동', householdCount: 700, yearBuilt: '2007', brand: '반도유보라건설' },
    { name: '반송동 나루마을 신도브래뉴', dong: '반송동', householdCount: 809, yearBuilt: '2007', brand: '신도종합건설' },
    { name: '반송동 나루마을 한화꿈에그린', dong: '반송동', householdCount: 784, yearBuilt: '2007', brand: '한화건설' },
    { name: '반송동 나루마을 한화꿈에그린우림필유', dong: '반송동', householdCount: 724, yearBuilt: '2007', brand: '한화건설' },
    { name: '반송동 메타폴리스', dong: '반송동', householdCount: 1266, yearBuilt: '2010', brand: '포스코건설' },
    { name: '반송동 센트럴포레스트', dong: '반송동', householdCount: 503, yearBuilt: '2009', brand: '신일건업' },
    { name: '반송동 솔빛마을 경남아너스빌', dong: '반송동', householdCount: 622, yearBuilt: '2007', brand: '경남기업' },
    { name: '반송동 솔빛마을 서해그랑블', dong: '반송동', householdCount: 727, yearBuilt: '2007', brand: '서해종합건설' },
    { name: '반송동 솔빛마을 신도브래뉴', dong: '반송동', householdCount: 584, yearBuilt: '2007', brand: '신도종합건설' },
    { name: '반송동 솔빛마을 쌍용예가', dong: '반송동', householdCount: 938, yearBuilt: '2007', brand: '쌍용건설' },
    { name: '반송동 시범 다은마을 동탄포스코더샵', dong: '반송동', householdCount: 514, yearBuilt: '2007', brand: '포스코건설' },
    { name: '반송동 시범 다은마을 메타역 롯데캐슬', dong: '반송동', householdCount: 429, yearBuilt: '2007', brand: '롯데건설' },
    { name: '반송동 시범 다은마을 삼성래미안', dong: '반송동', householdCount: 514, yearBuilt: '2007', brand: '삼성물산' },
    { name: '반송동 시범 다은마을 센트럴파크뷰', dong: '반송동', householdCount: 438, yearBuilt: '2008', brand: '풍성주택' },
    { name: '반송동 시범 다은마을 우남퍼스트빌', dong: '반송동', householdCount: 610, yearBuilt: '2007', brand: '우남건설' },
    { name: '반송동 시범 다은마을 월드메르디앙', dong: '반송동', householdCount: 1473, yearBuilt: '2007', brand: '월드건설' },
    { name: '반송동 시범 한빛마을 금호어울림', dong: '반송동', householdCount: 548, yearBuilt: '2007', brand: '금호건설' },
    { name: '반송동 시범 한빛마을 삼부르네상스', dong: '반송동', householdCount: 732, yearBuilt: '2007', brand: '삼부토건' },
    { name: '반송동 시범 한빛마을 아이파크', dong: '반송동', householdCount: 748, yearBuilt: '2007', brand: '현대산업개발' },
    { name: '반송동 시범 한빛마을 한화꿈에그린', dong: '반송동', householdCount: 534, yearBuilt: '2007', brand: '한화건설' },
    { name: '반송동 시범 한빛마을 KCC스위첸', dong: '반송동', householdCount: 484, yearBuilt: '2007', brand: 'KCC건설' },
  ],
  '산척동': [
    { name: '산척동 그린힐 반도유보라 아이비파크 10', dong: '산척동', householdCount: 1241, yearBuilt: '2018', brand: '반도건설' },
    { name: '산척동 더 레이크 파크뷰', dong: '산척동', householdCount: 641, yearBuilt: '2018', brand: '부영주택' },
    { name: '산척동 더 레이크 팰리스', dong: '산척동', householdCount: 706, yearBuilt: '2018', brand: '부영주택' },
    { name: '산척동 더레이크시티 부영 2단지', dong: '산척동', householdCount: 520, yearBuilt: '2018', brand: '부영주택' },
    { name: '산척동 더샵 레이크 에듀타운', dong: '산척동', householdCount: 1538, yearBuilt: '2019', brand: '포스코건설' },
    { name: '산척동 레이크힐 반도유보라 아이비파크 10.2', dong: '산척동', householdCount: 1515, yearBuilt: '2018', brand: '반도건설' },
    { name: '산척동 서희스타힐스 엔에이치에프', dong: '산척동', householdCount: 882, yearBuilt: '2017', brand: '서희건설' },
    { name: '산척동 중흥에스클래스 에듀하이', dong: '산척동', householdCount: 1194, yearBuilt: '2019', brand: '중봉건설' },
    { name: '호수공원 금강펜테리움 센트럴파크 Ⅱ', dong: '산척동', householdCount: 908, yearBuilt: '2017', brand: '금강주택' },
    { name: '호수공원역 레이크시티', dong: '산척동', householdCount: 818, yearBuilt: '2018', brand: '부영주택' },
    { name: '호수공원역 센트럴시티', dong: '산척동', householdCount: 1080, yearBuilt: '2019', brand: '부영주택' },
    { name: '호수공원역 센트리체', dong: '산척동', householdCount: 868, yearBuilt: '2018', brand: '부영주택' },
  ],
  '석우동': [
    { name: '석우동 예당마을 롯데캐슬', dong: '석우동', householdCount: 1222, yearBuilt: '2008', brand: '롯데건설' },
    { name: '석우동 예당마을 신일유토빌', dong: '석우동', householdCount: 626, yearBuilt: '2008', brand: '신일건업' },
    { name: '석우동 예당마을 우미린 제일풍경채', dong: '석우동', householdCount: 1316, yearBuilt: '2008', brand: '우미건설' },
    { name: '예당마을 푸르지오', dong: '석우동', householdCount: 978, yearBuilt: '2008', brand: '대우건설' },
  ],
  '송동': [
    { name: '송동 린스트라우스 더레이크', dong: '송동', householdCount: 956, yearBuilt: '2019', brand: '우미건설' },
    { name: '송동 하우스디 더레이크', dong: '송동', householdCount: 1552, yearBuilt: '2016', brand: '대보건설' },
  ],
  '신동': [
    { name: '신동 디에트르포레', dong: '신동', householdCount: 1171, yearBuilt: '2022', brand: '대방건설' },
  ],
  '여울동': [
    { name: '동탄역 더샵 센트럴시티 2차', dong: '여울동', householdCount: 745, yearBuilt: '2018', brand: '포스코건설' },
    { name: '동탄역 동원로얄듀크 비스타 3차', dong: '여울동', householdCount: 278, yearBuilt: '2020', brand: '동원개발' },
    { name: '동탄역 롯데캐슬', dong: '여울동', householdCount: 940, yearBuilt: '2021', brand: '롯데건설' },
    { name: '동탄역 린스트라우스', dong: '여울동', householdCount: 617, yearBuilt: '2018', brand: '우미건설' },
    { name: '동탄역 반도유보라 아이비파크 5.0', dong: '여울동', householdCount: 671, yearBuilt: '2018', brand: '반도건설' },
    { name: '동탄역 반도유보라 아이비파크 6.0', dong: '여울동', householdCount: 532, yearBuilt: '2017', brand: '반도건설' },
    { name: '동탄역 반도유보라 아이비파크 7.0', dong: '여울동', householdCount: 710, yearBuilt: '2019', brand: '반도건설' },
    { name: '동탄역 반도유보라 아이비파크 8.0', dong: '여울동', householdCount: 671, yearBuilt: '2018', brand: '반도건설' },
    { name: '동탄역 삼정그린코아 더베스트', dong: '여울동', householdCount: 183, yearBuilt: '2022', brand: '삼정건설' },
    { name: '동탄역 신미주', dong: '여울동', householdCount: 538, yearBuilt: '2005', brand: '풍성주택' },
    { name: '동탄역 에일린의뜰', dong: '여울동', householdCount: 489, yearBuilt: '2016', brand: '아이에스동서' },
    { name: '동탄역 예미지 시그너스', dong: '여울동', householdCount: 498, yearBuilt: '2021', brand: '금성백조주택' },
    { name: '동탄역 유림노르웨이숲', dong: '여울동', householdCount: 312, yearBuilt: '2021', brand: '유림이엔씨' },
    { name: '동탄역 중흥에스클래스', dong: '여울동', householdCount: 436, yearBuilt: '2019', brand: '중흥건설' },
    { name: '동탄역 파라곤', dong: '여울동', householdCount: 424, yearBuilt: '2021', brand: '동양건설산업' },
    { name: '동탄역 헤리엇', dong: '여울동', householdCount: 428, yearBuilt: '2023', brand: '현대비에스앤씨' },
    { name: '여울동 금강펜테리움 센트럴파크', dong: '여울동', householdCount: 827, yearBuilt: '2016', brand: '금강주택' },
    { name: '여울동 반도유보라 아이비파크 3.0', dong: '여울동', householdCount: 1135, yearBuilt: '2016', brand: '반도건설' },
    { name: '여울동 센트럴힐즈', dong: '여울동', householdCount: 652, yearBuilt: '2017', brand: '이수건설' },
  ],
  '영천동': [
    { name: '동탄 파크한양수자인', dong: '영천동', householdCount: 806, yearBuilt: '2019', brand: '한양' },
    { name: '동탄 퍼스트파크', dong: '영천동', householdCount: 470, yearBuilt: '2003', brand: '성원산업개발' },
    { name: '동탄역 경남아너스빌', dong: '영천동', householdCount: 344, yearBuilt: '2016', brand: '경남기업' },
    { name: '동탄역 대방디엠시티 더센텀', dong: '영천동', householdCount: 463, yearBuilt: '2021', brand: '대방건설' },
    { name: '동탄역 동원로얄듀크 1차', dong: '영천동', householdCount: 434, yearBuilt: '2018', brand: '동원개발' },
    { name: '동탄역 반도유보라 아이비파크 2.0', dong: '영천동', householdCount: 999, yearBuilt: '2016', brand: '반도건설' },
    { name: '동탄역 센트럴상록아파트', dong: '영천동', householdCount: 1005, yearBuilt: '2017', brand: '호반산업' },
    { name: '동탄역 센트럴예미지', dong: '영천동', householdCount: 451, yearBuilt: '2017', brand: '금성백조주택' },
    { name: '동탄역 센트럴자이', dong: '영천동', householdCount: 559, yearBuilt: '2015', brand: 'GS건설' },
    { name: '동탄역 이지더원', dong: '영천동', householdCount: 642, yearBuilt: '2015', brand: '라인' },
    { name: '동탄역 포레너스', dong: '영천동', householdCount: 1316, yearBuilt: '2017', brand: '부영주택' },
    { name: '동탄역 푸르지오', dong: '영천동', householdCount: 832, yearBuilt: '2017', brand: '대우건설' },
    { name: '영천동 동원로얄듀크포레 4차', dong: '영천동', householdCount: 196, yearBuilt: '2020', brand: '동원개발' },
    { name: '영천동 파크자이', dong: '영천동', householdCount: 979, yearBuilt: '2018', brand: '지에스건설' },
    { name: '영천동 파크푸르지오', dong: '영천동', householdCount: 913, yearBuilt: '2018', brand: '대우건설' },
    { name: '힐스테이트 동탄역', dong: '영천동', householdCount: 443, yearBuilt: '2020', brand: '현대건설' },
  ],
  '장지동': [
    { name: '동탄레이크 자연앤푸르지오', dong: '장지동', householdCount: 704, yearBuilt: '2020', brand: '대우건설' },
    { name: '동탄호수 자이파밀리에', dong: '장지동', householdCount: 1067, yearBuilt: '2018', brand: '지에스건설' },
    { name: '동탄호수 하우스디', dong: '장지동', householdCount: 516, yearBuilt: '2021', brand: '대보건설' },
    { name: '레이크 반도유보라 아이비파크 9.0', dong: '장지동', householdCount: 689, yearBuilt: '2017', brand: '반도건설' },
    { name: '장지동 금호 어울림 레이크', dong: '장지동', householdCount: 812, yearBuilt: '2018', brand: '금호산업' },
    { name: '장지동 금호어울림 레이크 2차', dong: '장지동', householdCount: 681, yearBuilt: '2019', brand: '금호건설' },
    { name: '장지동 아이파크 1단지', dong: '장지동', householdCount: 470, yearBuilt: '2019', brand: '현대산업개발' },
    { name: '장지동 아이파크 2단지', dong: '장지동', householdCount: 510, yearBuilt: '2019', brand: '현대산업개발' },
    { name: '장지동 제일풍경채 에듀앤파크', dong: '장지동', householdCount: 624, yearBuilt: '2018', brand: '제일건설' },
    { name: '장지동 호반베르디움', dong: '장지동', householdCount: 393, yearBuilt: '2018', brand: '호반건설' },
    { name: '한화포레나 동탄호수', dong: '장지동', householdCount: 800, yearBuilt: '2020', brand: '한화건설' },
  ],
  '청계동': [
    { name: '동탄역 대원칸타빌 포레지움', dong: '청계동', householdCount: 714, yearBuilt: '2015', brand: '대원' },
    { name: '동탄역 더힐', dong: '청계동', householdCount: 718, yearBuilt: '2017', brand: '부영주택' },
    { name: '동탄역 롯데캐슬 알바트로스', dong: '청계동', householdCount: 1416, yearBuilt: '2015', brand: '롯데건설' },
    { name: '동탄역 모아미래도', dong: '청계동', householdCount: 460, yearBuilt: '2015', brand: '모아종합건설' },
    { name: '동탄역 센트럴 푸르지오', dong: '청계동', householdCount: 1348, yearBuilt: '2015', brand: '대우건설' },
    { name: '동탄역 시범 금강펜테리움 센트럴파크 Ⅲ', dong: '청계동', householdCount: 252, yearBuilt: '2017', brand: '금강주택' },
    { name: '동탄역 시범 대원칸타빌', dong: '청계동', householdCount: 498, yearBuilt: '2015', brand: '대원' },
    { name: '동탄역 시범 더샵 센트럴시티', dong: '청계동', householdCount: 874, yearBuilt: '2015', brand: '포스코건설' },
    { name: '동탄역 시범 리슈빌', dong: '청계동', householdCount: 656, yearBuilt: '2015', brand: '계룡건설' },
    { name: '동탄역 시범 반도유보라 아이비파크 1.0', dong: '청계동', householdCount: 904, yearBuilt: '2015', brand: '반도건설' },
    { name: '동탄역 시범 반도유보라 아이비파크 4.0', dong: '청계동', householdCount: 740, yearBuilt: '2018', brand: '반도건설' },
    { name: '동탄역 시범 예미지', dong: '청계동', householdCount: 485, yearBuilt: '2015', brand: '금성백조주택' },
    { name: '동탄역 시범 우남퍼스트빌', dong: '청계동', householdCount: 1442, yearBuilt: '2015', brand: '우남건설' },
    { name: '동탄역 시범 한화꿈에그린 프레스티지', dong: '청계동', householdCount: 1817, yearBuilt: '2015', brand: '한화건설' },
    { name: '동탄역 시범 호반써밋', dong: '청계동', householdCount: 1002, yearBuilt: '2015', brand: '호반건설' },
    { name: '동탄역 신안인스빌리베라 1차', dong: '청계동', householdCount: 913, yearBuilt: '2015', brand: '신안' },
    { name: '동탄역 신안인스빌리베라 2차', dong: '청계동', householdCount: 644, yearBuilt: '2016', brand: '신안종합건설' },
    { name: '동탄역 호반써밋', dong: '청계동', householdCount: 922, yearBuilt: '2015', brand: '호반건설' },
    { name: '동탄역 KCC스위첸', dong: '청계동', householdCount: 640, yearBuilt: '2015', brand: 'KCC건설' },
  ],
};

/** 전체 아파트 수 */
export const TOTAL_APARTMENTS = Object.values(APARTMENTS_BY_DONG).flat().length;
